name: Localazy CI/CD Initializer
description: 'Decides whether to run "prepare" or "publish" job.'

inputs:
  run-after-install:
    description: Bash code to run after npm install.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

#    - name: Setup GitHub App Token
#      uses: tibdex/github-app-token@v2
#      id: auth
#      with:
#        app_id: ${{ inputs.app-id }}
#        private_key: ${{ inputs.app-key }}

    - name: Setup Git User
      uses: fregante/setup-git-user@v2

    - if: inputs.run-after-install != ''
      run: |
        echo -e "\n=== Run code after install ===\n"
        eval ${{ inputs.run-after-install }}
      shell: bash
