name: CI Init
description: 'Decides whether to run "prepare" or "publish" job.'

outputs:
  # TODO rename `action` to `job` in v3 release
  action:
    description: 'Detected job. Possible values "prepare" or "publish".'
    value: ${{ steps.detect.outputs.job }}

runs:
  using: composite
  steps:
    - run: echo "blue=\033[1;34m" >> $GITHUB_ENV
      shell: bash

    - run: echo -e "\n${{env.blue}}=== Detect next job ===\n"
      shell: bash

    - id: detect
      run: |
        IS_RELEASE=${{ github.event.head.ref == 'release' || startsWith(github.event.commits[0].message, '🚀 release:') }}
        if [ $IS_RELEASE == "true" ]; then echo "job=publish" >> "$GITHUB_OUTPUT" ; echo "Executing PUBLISH job" ; fi
        if [ $IS_RELEASE == "false" ]; then echo "job=prepare" >> "$GITHUB_OUTPUT" ; echo "Executing PREPARE job" ; fi
      shell: bash
