name: CI Init
description: Provides shared init steps for other actions

inputs:
  run-after-install:
    description: Bash code to run after npm install.
    required: false
    default: ''

outputs:
  action:
    description: 'Detected action. Possible values "prepare" or "publish".'
    value: ${{ steps.detect.outputs.action }}

runs:
  using: composite
  steps:
    - run: echo "blue=\033[1;34m" >> $GITHUB_ENV
      shell: bash

    - run: echo -e "\n${{env.blue}}=== Checkout repository ===\n"
      shell: bash

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - run: echo -e "\n${{env.blue}}=== Setup Node ===\n"
      shell: bash

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: echo -e "\n${{env.blue}}=== Install dependencies ===\n"
      shell: bash

    - run: |
        npm ci --ignore-scripts
        npm i -D conventional-changelog conventional-changelog-cli conventional-recommended-bump@9 https://github.com/localazy/conventional-changelog-preset.git#ci-changes https://github.com/localazy/conventional-changelog-writer.git
      shell: bash

    - run: echo -e "\n${{env.blue}}=== Run code after install ===\n"
      if: inputs.run-after-install != ''
      shell: bash

    - if: inputs.run-after-install != ''
      run: |
        eval ${{ inputs.run-after-install }}
      shell: bash

    - run: echo -e "\n${{env.blue}}=== Detect next action ===\n"
      shell: bash

    - id: detect
      run: |
        IS_RELEASE=${{ github.event.head.ref == 'release' || startsWith(github.event.commits[0].message, '🚀 release:') }}
        if [ $IS_RELEASE == "true" ]; then echo "action=publish" >> "$GITHUB_OUTPUT" ; echo "Executing PUBLISH action" ; fi
        if [ $IS_RELEASE == "false" ]; then echo "action=prepare" >> "$GITHUB_OUTPUT" ; echo "Executing PREPARE action" ; fi
      shell: bash
