name: Prepare Release PR
description: Create or update release branch and PR

inputs:
  app-id:
    description: GitHub app id.
    required: true

  app-key:
    description: GitHub app private key.
    required: true

  run-after-install:
    description: Bash code to run after npm install.
    required: false
    default: ''

  node-version:
    description: Node version.
    required: false
    default: '16'

  badges:
    description: Generate badges.
    required: false

  badges-coverage:
    description: ''
    required: false
    default: >
      node -p "require('./coverage/coverage-summary.json').total.lines.pct"

  badges-size:
    description: ''
    required: false
    default: ''

  badges-version:
    description: ''
    required: false
    default: > 
      node -p "require('./package.json').version"

  badges-license:
    description: ''
    required: false
    default: >
      node -p "require('./package.json').license"

  badges-size-command:
    description: ''
    required: false
    default: >
      npm run build

  badges-coverage-command:
    description: ''
    required: false
    default: >
      npm run test:coverage

  monorepo-bump:
    description: Monorepo paths.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - uses: localazy/release/setup-npm@v2
      with:
        run-after-install: ${{ inputs.run-after-install }}
        node-version: ${{ inputs.node-version }}

    - run: echo -e "\n${{env.blue}}=== Setup GitHub app authorization ===\n"
      shell: bash

    - id: auth
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.app-key }}

    - run: echo -e "\n${{env.blue}}=== Bump package.json version ===\n"
      shell: bash

    - id: recommended-bump
      run: |
        BUMP_TYPE=$(npx conventional-recommended-bump -p @localazy/conventional-changelog-preset)
        echo "type=$BUMP_TYPE" >> "$GITHUB_OUTPUT"
      shell: bash

    - if: inputs.monorepo-bump == 'false'
      run: |
        npm version ${{ steps.recommended-bump.outputs.type }} --git-tag-version false
      shell: bash

    - if: inputs.monorepo-bump != 'false'
      run: |
        PROJECT_ROOT=$(pwd)
        declare -a BUMP_LIST=(${{ inputs.monorepo-bump }})
        for item in "${BUMP_LIST[@]}"; do
          cd $PROJECT_ROOT
          cd "$item"
          npm version ${{ steps.recommended-bump.outputs.type }} --git-tag-version false
        done
      shell: bash

    - id: bump
      run: |
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        echo "package-version=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
      shell: bash

    - run: echo -e "\n${{env.blue}}=== Generate changelog preview for PR ===\n"
      shell: bash

    - id: changelog
      run: |
        {
          echo 'changelog-preview<<EOF'
          npx conventional-changelog -p @localazy/preset -c node_modules/@localazy/conventional-changelog-preset/config/short-pr.json -u
          echo EOF
        } >> "$GITHUB_OUTPUT"
      shell: bash

    - run: echo -e "\n${{env.blue}}=== Update CHANGELOG.md ===\n"
      shell: bash

    - run: npx conventional-changelog -p @localazy/preset -u -i CHANGELOG.md -s
      shell: bash

    - if: inputs.badges == 'true'
      run: echo -e "\n${{env.blue}}=== Generate badges ===\n"
      shell: bash

    - if: inputs.badges == 'true'
      id: data
      run: |
        $(echo "${{ inputs.badges-size-command }}")
        $(echo "${{ inputs.badges-coverage-command }}")

        VERSION=$(${{ inputs.badges-version }})
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

        LICENSE=$(${{ inputs.badges-license }})
        echo "license=$LICENSE" >> "$GITHUB_OUTPUT"

        COVERAGE=$(${{ inputs.badges-coverage }})
        echo "coverage=$COVERAGE" >> "$GITHUB_OUTPUT"

        if [ "${{ inputs.badges-size }}" != "" ]
        then
          SIZE=$(gzip -c ${{ inputs.badges-size }} | wc -c);
          echo "size=$SIZE" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - if: inputs.badges == 'true'
      uses: localazy/release/generate-badges@v2
      with:
        version: ${{ steps.data.outputs.version }}
        license: ${{ steps.data.outputs.license }}
        coverage: ${{ steps.data.outputs.coverage }}
        size: ${{ steps.data.outputs.size }}

    - run: echo -e "\n${{env.blue}}=== Clean changelog npm deps ===\n"
      shell: bash

    - run: npm r conventional-changelog conventional-changelog-cli conventional-recommended-bump @localazy/conventional-changelog-preset conventional-changelog-writer
      shell: bash

    - run: echo -e "\n${{env.blue}}=== Prepare release branch and create PR ===\n"
      shell: bash

    - uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ steps.auth.outputs.token }}
        branch: release
        labels: release-preview
        commit-message: "🚀 release: ${{ steps.bump.outputs.package-version }}"
        title: ${{ steps.bump.outputs.package-version }}
        body: ${{ steps.changelog.outputs.changelog-preview }}
