export const SemverDefinitions = [
  {
    id: 'breaking',
    aliases: ['breaking'],
    emojis: ['💥'],
    versionIncrease: 'major',
    heading: '💥 Breaking Changes',
    changelog: {
      category: 'breaking',
      heading: '💥 Breaking Changes',
      order: 10,
    },
  },
  {
    id: 'feature',
    aliases: ['feature', 'feat'],
    emojis: ['✨', '🌟', '💫', '🌠'],
    versionIncrease: 'minor',
    heading: '✨ Features',
    changelog: {
      category: 'feature',
      heading: '✨ Features',
      order: 20,
    },
  },
  {
    id: 'performance',
    aliases: ['performance', 'perf'],
    emojis: ['⚡️'],
    versionIncrease: 'patch',
    heading: '⚡️ Performance',
    changelog: {
      category: 'performance',
      heading: '⚡️ Performance',
      order: 30,
    },
  },
  {
    id: 'fixes',
    aliases: ['fixes', 'fix', 'hotfix', 'hotfixes'],
    emojis: ['🐛', '🐞', '🚑', '🚨'],
    versionIncrease: 'patch',
    heading: '🐛 Bug Fixes',
    changelog: {
      category: 'fixes',
      heading: '🐛 Bug Fixes',
      order: 40,
    },
  },
  {
    id: 'docs',
    aliases: ['docs', 'doc'],
    emojis: ['📚', '📖', '📝'],
    versionIncrease: 'patch',
    heading: '📚 Documentation',
    changelog: {
      category: 'docs',
      heading: '📚 Documentation',
      order: 50,
    },
  },
  {
    id: 'tests',
    aliases: ['tests', 'test'],
    emojis: ['🧪', '✅', '🚦'],
    versionIncrease: 'patch',
    heading: '🧪 Tests',
    changelog: {
      category: 'tests',
      heading: '🧪 Tests',
      order: 60,
    },
  },
  {
    id: 'refactor',
    aliases: ['refactor'],
    emojis: ['♻️', '🦄'],
    versionIncrease: 'patch',
    heading: '♻️ Refactor',
    changelog: {
      category: 'other',
      heading: '🧰 Other Commits',
      order: 70,
    },
  },
  {
    id: 'style',
    aliases: ['style', 'cleanup', 'format', 'lint'],
    emojis: ['💄', '🎨', '🌈'],
    versionIncrease: 'patch',
    heading: '💄 Style',
    changelog: {
      category: 'other',
      heading: '🧰 Other Commits',
      order: 71,
    },
  },
  {
    id: 'chore',
    aliases: ['chore', 'chores', 'deps', 'build', 'ci'],
    emojis: ['🔧', '⚙️', '🏗', '⬆️'],
    versionIncrease: 'patch',
    heading: '🔧 Chores',
    changelog: {
      category: 'other',
      heading: '🧰 Other Commits',
      order: 72,
    },
  },
  {
    id: 'prerelease',
    aliases: ['prerelease'],
    emojis: ['🚧'],
    versionIncrease: 'none',
    heading: '🚧 Prerelease',
    changelog: 'none',
  },
  {
    id: 'release',
    aliases: ['release'],
    emojis: ['🚀'],
    versionIncrease: 'none',
    heading: '🚀 Release',
    changelog: 'none',
  },
] as const;
