name: Localazy CI
description: ''

inputs:
  app-id:
    description: GitHub app id.
    required: true

  app-key:
    description: GitHub app private key.
    required: true

  run-after-setup:
    description: Bash code to run after setup.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - if: "!env.ACT"
      name: Setup GitHub App Token
      uses: tibdex/github-app-token@v2
      id: auth
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.app-key }}

    - name: Setup Git User
      uses: fregante/setup-git-user@v2

    - if: inputs.run-after-setup != ''
      name: Run after setup
      run: |
        eval ${{ inputs.run-after-setup }}
      shell: bash

    - name: Release CI
      uses: ./release-ci
      id: ci

    - name: verify outputs
      shell: bash
      run: |
        echo "package-version:"
        echo "${{ steps.ci.outputs.package-version }}"
        echo "changelog-pr:"
        echo "${{ steps.ci.outputs.changelog-pr }}"

#    - name: Create Release PR
#      uses: peter-evans/create-pull-request@v6
#      with:
#        token: ${{ steps.setup.outputs.token }}
#        branch: release
#        base: wip_pr_target
#        delete-branch: 'false'
#        labels: release-preview
#        commit-message: "🚀 release: ${{ steps.ci.outputs.package-version }}"
#        title: ${{ steps.ci.outputs.package-version }}
#        body: ${{ steps.ci.outputs.changelog-pr }}
