name: Localazy CI
description: ''

inputs:
  app-id:
    description: GitHub app id.
    required: true

  app-key:
    description: GitHub app private key.
    required: true

  run-after-setup:
    description: Bash code to run after setup.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup CI
      id: setup
      uses: ./setup
      with:
        app-id: ${{ inputs.app-id }}
        app-key: ${{ inputs.app-key }}
        run-after-setup: ${{ inputs.run-after-setup }}

    - name: Release CI
      id: ci
      uses: ./release-ci

    - name: verify outputs
      shell: bash
      run: |
        echo "package-version: ${{ env.ACT }}"
        echo "package-version:"
        echo "${{ steps.ci.outputs.package-version }}"
        echo "changelog-pr:"
        echo "${{ steps.ci.outputs.changelog-pr }}"

#    - if: "!env.ACT"
#      name: Create Release PR
#      uses: peter-evans/create-pull-request@v6
#      with:
#        token: ${{ steps.setup.outputs.token }}
#        branch: release
#        base: wip_pr_target
#        delete-branch: 'false'
#        labels: release-preview
#        commit-message: "🚀 release: ${{ steps.ci.outputs.package-version }}"
#        title: ${{ steps.ci.outputs.package-version }}
#        body: ${{ steps.ci.outputs.changelog-pr }}
