import { OctokitWorkflowContext } from '../../../model/octokit/octokit-workflow-context';

import { IGetWorkflowContextOptions } from '../../../model/commands/context/i-get-workflow-context-options';

export async function getWorkflowContext({
  octokit,
  owner,
  repo,
  runId,
}: IGetWorkflowContextOptions): Promise<OctokitWorkflowContext | null> {
  try {
    const { data } = await octokit.rest.actions.getWorkflowRun({
      owner,
      repo,
      run_id: Number(runId),
    });

    return data;
  } catch (err) {
    console.error('Error fetching workflow context:', err);
    return null;
  }
}

/*
| Workflow context: {
|   id: 9271808588,
|   name: 'QA checks',
|   node_id: 'WFR_kwLOKr4MA88AAAACKKSSTA',
|   head_branch: 'test_monorepo',
|   head_sha: '1db866a40ff174248e107914c518463860a33d46',
|   path: '.github/workflows/qa.yml',
|   display_title: '🔧 chore: CI',
|   run_number: 21,
|   event: 'push',
|   status: 'completed',
|   conclusion: 'success',
|   workflow_id: 75713873,
|   check_suite_id: 24263144021,
|   check_suite_node_id: 'CS_kwDOKr4MA88AAAAFpjIyVQ',
|   url: 'https://api.github.com/repos/localazy/ci-sandbox/actions/runs/9271808588',
|   html_url: 'https://github.com/localazy/ci-sandbox/actions/runs/9271808588',
|   pull_requests: [],
|   created_at: '2024-05-28T15:05:14Z',
|   updated_at: '2024-05-28T15:05:27Z',
|   actor: {
|     login: 'honzabubenik',
|     id: 138865634,
|     node_id: 'U_kgDOCEbr4g',
|     avatar_url: 'https://avatars.githubusercontent.com/u/138865634?v=4',
|     gravatar_id: '',
|     url: 'https://api.github.com/users/honzabubenik',
|     html_url: 'https://github.com/honzabubenik',
|     followers_url: 'https://api.github.com/users/honzabubenik/followers',
|     following_url: 'https://api.github.com/users/honzabubenik/following{/other_user}',
|     gists_url: 'https://api.github.com/users/honzabubenik/gists{/gist_id}',
|     starred_url: 'https://api.github.com/users/honzabubenik/starred{/owner}{/repo}',
|     subscriptions_url: 'https://api.github.com/users/honzabubenik/subscriptions',
|     organizations_url: 'https://api.github.com/users/honzabubenik/orgs',
|     repos_url: 'https://api.github.com/users/honzabubenik/repos',
|     events_url: 'https://api.github.com/users/honzabubenik/events{/privacy}',
|     received_events_url: 'https://api.github.com/users/honzabubenik/received_events',
|     type: 'User',
|     user_view_type: 'public',
|     site_admin: false
|   },
|   run_attempt: 1,
|   referenced_workflows: [],
|   run_started_at: '2024-05-28T15:05:14Z',
|   triggering_actor: {
|     login: 'honzabubenik',
|     id: 138865634,
|     node_id: 'U_kgDOCEbr4g',
|     avatar_url: 'https://avatars.githubusercontent.com/u/138865634?v=4',
|     gravatar_id: '',
|     url: 'https://api.github.com/users/honzabubenik',
|     html_url: 'https://github.com/honzabubenik',
|     followers_url: 'https://api.github.com/users/honzabubenik/followers',
|     following_url: 'https://api.github.com/users/honzabubenik/following{/other_user}',
|     gists_url: 'https://api.github.com/users/honzabubenik/gists{/gist_id}',
|     starred_url: 'https://api.github.com/users/honzabubenik/starred{/owner}{/repo}',
|     subscriptions_url: 'https://api.github.com/users/honzabubenik/subscriptions',
|     organizations_url: 'https://api.github.com/users/honzabubenik/orgs',
|     repos_url: 'https://api.github.com/users/honzabubenik/repos',
|     events_url: 'https://api.github.com/users/honzabubenik/events{/privacy}',
|     received_events_url: 'https://api.github.com/users/honzabubenik/received_events',
|     type: 'User',
|     user_view_type: 'public',
|     site_admin: false
|   },
|   jobs_url: 'https://api.github.com/repos/localazy/ci-sandbox/actions/runs/9271808588/jobs',
|   logs_url: 'https://api.github.com/repos/localazy/ci-sandbox/actions/runs/9271808588/logs',
|   check_suite_url: 'https://api.github.com/repos/localazy/ci-sandbox/check-suites/24263144021',
|   artifacts_url: 'https://api.github.com/repos/localazy/ci-sandbox/actions/runs/9271808588/artifacts',
|   cancel_url: 'https://api.github.com/repos/localazy/ci-sandbox/actions/runs/9271808588/cancel',
|   rerun_url: 'https://api.github.com/repos/localazy/ci-sandbox/actions/runs/9271808588/rerun',
|   previous_attempt_url: null,
|   workflow_url: 'https://api.github.com/repos/localazy/ci-sandbox/actions/workflows/75713873',
|   head_commit: {
|     id: '1db866a40ff174248e107914c518463860a33d46',
|     tree_id: 'e10aa174c835df24a8b21511c49d5fd11c0a8a72',
|     message: '🔧 chore: CI',
|     timestamp: '2024-05-28T15:05:10Z',
|     author: { name: 'Honza Bubeník', email: 'honza.bubenik@localazy.com' },
|     committer: { name: 'Honza Bubeník', email: 'honza.bubenik@localazy.com' }
|   },
|   repository: {
|     id: 717097987,
|     node_id: 'R_kgDOKr4MAw',
|     name: 'ci-sandbox',
|     full_name: 'localazy/ci-sandbox',
|     private: true,
|     owner: {
|       login: 'localazy',
|       id: 59409404,
|       node_id: 'MDEyOk9yZ2FuaXphdGlvbjU5NDA5NDA0',
|       avatar_url: 'https://avatars.githubusercontent.com/u/59409404?v=4',
|       gravatar_id: '',
|       url: 'https://api.github.com/users/localazy',
|       html_url: 'https://github.com/localazy',
|       followers_url: 'https://api.github.com/users/localazy/followers',
|       following_url: 'https://api.github.com/users/localazy/following{/other_user}',
|       gists_url: 'https://api.github.com/users/localazy/gists{/gist_id}',
|       starred_url: 'https://api.github.com/users/localazy/starred{/owner}{/repo}',
|       subscriptions_url: 'https://api.github.com/users/localazy/subscriptions',
|       organizations_url: 'https://api.github.com/users/localazy/orgs',
|       repos_url: 'https://api.github.com/users/localazy/repos',
|       events_url: 'https://api.github.com/users/localazy/events{/privacy}',
|       received_events_url: 'https://api.github.com/users/localazy/received_events',
|       type: 'Organization',
|       user_view_type: 'public',
|       site_admin: false
|     },
|     html_url: 'https://github.com/localazy/ci-sandbox',
|     description: 'Sandbox repository for CI testing',
|     fork: false,
|     url: 'https://api.github.com/repos/localazy/ci-sandbox',
|     forks_url: 'https://api.github.com/repos/localazy/ci-sandbox/forks',
|     keys_url: 'https://api.github.com/repos/localazy/ci-sandbox/keys{/key_id}',
|     collaborators_url: 'https://api.github.com/repos/localazy/ci-sandbox/collaborators{/collaborator}',
|     teams_url: 'https://api.github.com/repos/localazy/ci-sandbox/teams',
|     hooks_url: 'https://api.github.com/repos/localazy/ci-sandbox/hooks',
|     issue_events_url: 'https://api.github.com/repos/localazy/ci-sandbox/issues/events{/number}',
|     events_url: 'https://api.github.com/repos/localazy/ci-sandbox/events',
|     assignees_url: 'https://api.github.com/repos/localazy/ci-sandbox/assignees{/user}',
|     branches_url: 'https://api.github.com/repos/localazy/ci-sandbox/branches{/branch}',
|     tags_url: 'https://api.github.com/repos/localazy/ci-sandbox/tags',
|     blobs_url: 'https://api.github.com/repos/localazy/ci-sandbox/git/blobs{/sha}',
|     git_tags_url: 'https://api.github.com/repos/localazy/ci-sandbox/git/tags{/sha}',
|     git_refs_url: 'https://api.github.com/repos/localazy/ci-sandbox/git/refs{/sha}',
|     trees_url: 'https://api.github.com/repos/localazy/ci-sandbox/git/trees{/sha}',
|     statuses_url: 'https://api.github.com/repos/localazy/ci-sandbox/statuses/{sha}',
|     languages_url: 'https://api.github.com/repos/localazy/ci-sandbox/languages',
|     stargazers_url: 'https://api.github.com/repos/localazy/ci-sandbox/stargazers',
|     contributors_url: 'https://api.github.com/repos/localazy/ci-sandbox/contributors',
|     subscribers_url: 'https://api.github.com/repos/localazy/ci-sandbox/subscribers',
|     subscription_url: 'https://api.github.com/repos/localazy/ci-sandbox/subscription',
|     commits_url: 'https://api.github.com/repos/localazy/ci-sandbox/commits{/sha}',
|     git_commits_url: 'https://api.github.com/repos/localazy/ci-sandbox/git/commits{/sha}',
|     comments_url: 'https://api.github.com/repos/localazy/ci-sandbox/comments{/number}',
|     issue_comment_url: 'https://api.github.com/repos/localazy/ci-sandbox/issues/comments{/number}',
|     contents_url: 'https://api.github.com/repos/localazy/ci-sandbox/contents/{+path}',
|     compare_url: 'https://api.github.com/repos/localazy/ci-sandbox/compare/{base}...{head}',
|     merges_url: 'https://api.github.com/repos/localazy/ci-sandbox/merges',
|     archive_url: 'https://api.github.com/repos/localazy/ci-sandbox/{archive_format}{/ref}',
|     downloads_url: 'https://api.github.com/repos/localazy/ci-sandbox/downloads',
|     issues_url: 'https://api.github.com/repos/localazy/ci-sandbox/issues{/number}',
|     pulls_url: 'https://api.github.com/repos/localazy/ci-sandbox/pulls{/number}',
|     milestones_url: 'https://api.github.com/repos/localazy/ci-sandbox/milestones{/number}',
|     notifications_url: 'https://api.github.com/repos/localazy/ci-sandbox/notifications{?since,all,participating}',
|     labels_url: 'https://api.github.com/repos/localazy/ci-sandbox/labels{/name}',
|     releases_url: 'https://api.github.com/repos/localazy/ci-sandbox/releases{/id}',
|     deployments_url: 'https://api.github.com/repos/localazy/ci-sandbox/deployments'
|   },
|   head_repository: {
|     id: 717097987,
|     node_id: 'R_kgDOKr4MAw',
|     name: 'ci-sandbox',
|     full_name: 'localazy/ci-sandbox',
|     private: true,
|     owner: {
|       login: 'localazy',
|       id: 59409404,
|       node_id: 'MDEyOk9yZ2FuaXphdGlvbjU5NDA5NDA0',
|       avatar_url: 'https://avatars.githubusercontent.com/u/59409404?v=4',
|       gravatar_id: '',
|       url: 'https://api.github.com/users/localazy',
|       html_url: 'https://github.com/localazy',
|       followers_url: 'https://api.github.com/users/localazy/followers',
|       following_url: 'https://api.github.com/users/localazy/following{/other_user}',
|       gists_url: 'https://api.github.com/users/localazy/gists{/gist_id}',
|       starred_url: 'https://api.github.com/users/localazy/starred{/owner}{/repo}',
|       subscriptions_url: 'https://api.github.com/users/localazy/subscriptions',
|       organizations_url: 'https://api.github.com/users/localazy/orgs',
|       repos_url: 'https://api.github.com/users/localazy/repos',
|       events_url: 'https://api.github.com/users/localazy/events{/privacy}',
|       received_events_url: 'https://api.github.com/users/localazy/received_events',
|       type: 'Organization',
|       user_view_type: 'public',
|       site_admin: false
|     },
|     html_url: 'https://github.com/localazy/ci-sandbox',
|     description: 'Sandbox repository for CI testing',
|     fork: false,
|     url: 'https://api.github.com/repos/localazy/ci-sandbox',
|     forks_url: 'https://api.github.com/repos/localazy/ci-sandbox/forks',
|     keys_url: 'https://api.github.com/repos/localazy/ci-sandbox/keys{/key_id}',
|     collaborators_url: 'https://api.github.com/repos/localazy/ci-sandbox/collaborators{/collaborator}',
|     teams_url: 'https://api.github.com/repos/localazy/ci-sandbox/teams',
|     hooks_url: 'https://api.github.com/repos/localazy/ci-sandbox/hooks',
|     issue_events_url: 'https://api.github.com/repos/localazy/ci-sandbox/issues/events{/number}',
|     events_url: 'https://api.github.com/repos/localazy/ci-sandbox/events',
|     assignees_url: 'https://api.github.com/repos/localazy/ci-sandbox/assignees{/user}',
|     branches_url: 'https://api.github.com/repos/localazy/ci-sandbox/branches{/branch}',
|     tags_url: 'https://api.github.com/repos/localazy/ci-sandbox/tags',
|     blobs_url: 'https://api.github.com/repos/localazy/ci-sandbox/git/blobs{/sha}',
|     git_tags_url: 'https://api.github.com/repos/localazy/ci-sandbox/git/tags{/sha}',
|     git_refs_url: 'https://api.github.com/repos/localazy/ci-sandbox/git/refs{/sha}',
|     trees_url: 'https://api.github.com/repos/localazy/ci-sandbox/git/trees{/sha}',
|     statuses_url: 'https://api.github.com/repos/localazy/ci-sandbox/statuses/{sha}',
|     languages_url: 'https://api.github.com/repos/localazy/ci-sandbox/languages',
|     stargazers_url: 'https://api.github.com/repos/localazy/ci-sandbox/stargazers',
|     contributors_url: 'https://api.github.com/repos/localazy/ci-sandbox/contributors',
|     subscribers_url: 'https://api.github.com/repos/localazy/ci-sandbox/subscribers',
|     subscription_url: 'https://api.github.com/repos/localazy/ci-sandbox/subscription',
|     commits_url: 'https://api.github.com/repos/localazy/ci-sandbox/commits{/sha}',
|     git_commits_url: 'https://api.github.com/repos/localazy/ci-sandbox/git/commits{/sha}',
|     comments_url: 'https://api.github.com/repos/localazy/ci-sandbox/comments{/number}',
|     issue_comment_url: 'https://api.github.com/repos/localazy/ci-sandbox/issues/comments{/number}',
|     contents_url: 'https://api.github.com/repos/localazy/ci-sandbox/contents/{+path}',
|     compare_url: 'https://api.github.com/repos/localazy/ci-sandbox/compare/{base}...{head}',
|     merges_url: 'https://api.github.com/repos/localazy/ci-sandbox/merges',
|     archive_url: 'https://api.github.com/repos/localazy/ci-sandbox/{archive_format}{/ref}',
|     downloads_url: 'https://api.github.com/repos/localazy/ci-sandbox/downloads',
|     issues_url: 'https://api.github.com/repos/localazy/ci-sandbox/issues{/number}',
|     pulls_url: 'https://api.github.com/repos/localazy/ci-sandbox/pulls{/number}',
|     milestones_url: 'https://api.github.com/repos/localazy/ci-sandbox/milestones{/number}',
|     notifications_url: 'https://api.github.com/repos/localazy/ci-sandbox/notifications{?since,all,participating}',
|     labels_url: 'https://api.github.com/repos/localazy/ci-sandbox/labels{/name}',
|     releases_url: 'https://api.github.com/repos/localazy/ci-sandbox/releases{/id}',
|     deployments_url: 'https://api.github.com/repos/localazy/ci-sandbox/deployments'
|   }
| }

 */
