name: 💙 Localazy CD Release
description: ''

inputs:
  token:
    description: GitHub app token.
    required: true

  package-version:
    description: Package version.
    required: true

  changelog-pr:
    description: Changelog for pull request.
    required: true

  changelog-github-release:
    description: Changelog for GitHub release.
    required: true

  next-action:
    description: 'Possible values: "create-pull-request" or "create-github-release".'
    required: true

runs:
  using: composite
  steps:
    - if: "inputs.next-action == 'create-pull-request' && !env.ACT"
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.token }}
        branch: wip_release
        base: wip_pr_target
        delete-branch: 'false'
        labels: release-preview
        commit-message: "🚀 release: ${{ inputs.package-version }}"
        title: ${{ inputs.package-version }}
        body: ${{ inputs.changelog-pr }}

    - if: "inputs.next-action == 'create-github-release' && !env.ACT"
      name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ inputs.token }}
        name: ${{ inputs.package-version }}
        tag: ${{ inputs.package-version }}
        body: ${{ inputs.changelog-github-release }}
        skipIfReleaseExists: true
