name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 💙 Localazy CI - Setup
        id: setup
        uses: ./ci/setup
        with:
          app-id: ${{ secrets.AUTH_APP_ID }}
          app-key: ${{ secrets.AUTH_APP_KEY }}

      - name: 💙 Localazy CI - Version Management
        id: version-management
        uses: ./ci/version-management

      - if: "steps.version-management.outputs.next-action == 'create-pull-request'"
        name: 💙 Localazy CD - Create Pull Request
        run: |
          echo "Create Pull Request"
          echo "Package Version: ${{ steps.version-management.outputs.package-version }}"
          echo "Changelog PR: ${{ steps.version-management.outputs.changelog-pr }}"

      #      - if: "steps.version-management.outputs.next-action == 'create-github-release' && !env.ACT"
      #        name: 💙 Localazy CD - Create Github Release
      #        uses: ./cd/create-github-release
      #        with:
      #          token: ${{ steps.setup.outputs.token }}
      #          package-version: ${{ steps.version-management.outputs.package-version }}
      #          changelog-github-release: ${{ steps.version-management.outputs.changelog-github-release }}

      - if: "steps.version-management.outputs.next-action == 'create-pull-request' && !env.ACT"
        name: 💙 Localazy CD - Create Pull Request
        uses: ./cd/create-pull-request
        with:
          token: ${{ steps.setup.outputs.token }}
          package-version: ${{ steps.version-management.outputs.package-version }}
          changelog-pr: ${{ steps.version-management.outputs.changelog-pr }}

      - if: "steps.version-management.outputs.next-action == 'create-github-release'"
        name: 💙 Localazy CD - Create Github Release
        run: |
          echo "Create Github Release"
          echo "Package Version: ${{ steps.version-management.outputs.package-version }}"
          echo "Changelog Github Release: ${{ steps.version-management.outputs.changelog-github-release }}"
