name: CI
on:
  push:
    branches:
      - wip_release_update

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 💙 Localazy CI - Setup
        id: setup
        uses: ./ci/setup
        with:
          app-id: ${{ secrets.AUTH_APP_ID }}
          app-key: ${{ secrets.AUTH_APP_KEY }}

      - name: 💙 Localazy CI - Release Management
        id: release-management
        uses: ./ci/release-management

      - if: "steps.release-management.outputs.next-action == 'create-pull-request'"
        name: 💙 Localazy CD - Create Pull Request
        run: |
          echo "Create Pull Request"
          echo "Package Version: ${{ steps.release-management.outputs.package-version }}"
          echo "Changelog PR: ${{ steps.release-management.outputs.changelog-pull-request }}"

      - if: "steps.release-management.outputs.next-action == 'create-github-release'"
        name: 💙 Localazy CD - Create Github Release
        run: |
          echo "Create Github Release"
          echo "Package Version: ${{ steps.release-management.outputs.package-version }}"
          echo "Changelog Github Release: ${{ steps.release-management.outputs.changelog-github-release }}"

      #      - if: "steps.release-management.outputs.next-action == 'create-github-release' && !env.ACT"
      #        name: 💙 Localazy CD - Create Github Release
      #        uses: ./cd/create-github-release
      #        with:
      #          token: ${{ steps.setup.outputs.token }}
      #          package-version: ${{ steps.release-management.outputs.package-version }}
      #          changelog-github-release: ${{ steps.release-management.outputs.changelog-github-release }}

      #      - if: "steps.release-management.outputs.next-action == 'create-pull-request' && !env.ACT"
      #        name: 💙 Localazy CD - Create Pull Request
      #        uses: ./cd/create-pull-request
      #        with:
      #          token: ${{ steps.setup.outputs.token }}
      #          package-version: ${{ steps.release-management.outputs.package-version }}
      #          changelog-pull-request: ${{ steps.release-management.outputs.changelog-pull-request }}
